Added data provider module with demo notebook
konev-artem/FewShotLearning pull request #2
Opened 2019-03-20 06:53 UTC by bobbythehiver

2019-03-21 18:53 UTC, vladiprof requested changes
1) Нужно добавить методы для разбиения датасета на два непересекающиеся по классам в соотвествии с процентом
2) При генерации эпизода нужно еще генерировать queryset
3) Не ясно как применять аугументатор
4) Размер батча - это параметр генератора, а не самого датасета
5) Не смог запустить ноутбук:
 65         super(DataFrameIterator, self).common_init(image_data_generator,
     66                                                    target_size,
     67                                                    'rgb',

AttributeError: 'super' object has no attribute 'common_init'
у меня python 3.7.2 tf-1.13.1

2019-03-21 22:50 UTC, MokriyYuriy commented on data_provider/dataset.py
> +                 val_generator_args={},
Давай всё таки вынесем логику про трейн и валидацию за датасет, чтобы не дублировать всё под два раза. Например, можно сделать два метода у класса: split_by_classes, split_by_objects. Оба возвращают два объекта Dataset.  Как я понял, ты всё делаешь, через index - следовательно, эти два датасета будут отличаться только этим индексом.

2019-03-21 22:50 UTC, MokriyYuriy commented on data_provider/dataset.py
> +from keras_preprocessing.image import ImageDataGenerator
Это потом заменится на наши собственные аугментации, поэтому это сейчас можно выпилить. В целом, мне нравится такое: у датасета будет поле random_transform, в котором изначально будет какой-то identity трансформер  + у класса датасет есть метод with_random_transformer(random_transformer), которая возвращает новый Dataset с изменённым полем random_transform.

2019-03-21 22:50 UTC, MokriyYuriy commented on data_provider/dataset.py
> +        self.categorical_col = list(categorical_col)
x_col и image_col, y_col и categorical_col - точно не одно и тоже в нашей задаче?

2019-03-27 10:10 UTC, bobbythehiver commented on data_provider/dataset.py
> +        self.categorical_col = list(categorical_col)
да, какие-то вещи для нашей задачи, пожалуй, избыточны. сейчас сделала менее универсальным и более понятным.

2019-03-27 10:10 UTC, bobbythehiver commented on data_provider/dataset.py
> +                 val_generator_args={},
звучит логично, сделала

2019-04-03 09:37 UTC, konev-artem commented on data_provider/dataset.py
> +from keras_preprocessing.image import ImageDataGenerator as Transformer # will change for custom implementation later
@infected-mushroom обрати внимание, как тут используется класс Transformer

2019-04-03 09:37 UTC, konev-artem commented on data_provider/generator.py
> +                 interpolation='nearest',
мы можем по дефолту хотя бы bilinear использвать?

2019-04-03 09:37 UTC, konev-artem commented on data_provider/generator.py
> +            img_arr = keras_img.img_to_array(img) / 255.
зачем? в текущей агументации от @infected-mushroom мы такого поворота (вроде бы) не ожидаем

2019-04-03 09:37 UTC, konev-artem commented on data_provider/generator.py
> +        seed = np.random.randint(1000000)
ну тут seed хотя бы в параметры (и по умолчанию ты же использовала 42 в другом месте)

2019-04-03 09:37 UTC, konev-artem commented on data_provider/generator.py
> +                np.random.choice(self.y[self.y==class_name].index, size=self.n_shot) \
мы всегда будем рандомный subsample возвращать? если да, то разве во время тестирования правильно так делать?

2019-04-03 20:33 UTC, konev-artem commented on data_provider/generator.py
> +            index_array = np.concatenate([
не хватает возврата query set'a

2019-04-07 10:45 UTC, closed without merging