augmentation module
konev-artem/FewShotLearning pull request #4
Opened 2019-03-29 18:57 UTC by infected-mushroom

Added some augmentation methods including mixed-example. 
To do: add more mixed-example methods.

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +    pass
лучше raise NotImplementedError

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +            img = f(img1, img2, y1, y2)
здесь что-то странное проиходит: мы можем вызвать много трансформаций и будем использовать только последнюю из них?

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +    return crop(img, left, lower, h, w)
обычно мы знаем, какого размер кроп хотим получить: например, вырезать 28x28 из 32x32 (+полезно иметь возможность передать параметром, чтобы вырезалось по центру), а на выходе можно вообще пустой выход получить (если h или w =0)

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +        if random.random() < p:
надо подумать, не лучше ли будет эту вероятность p внутрь самих функций передавать
например, если мы во время тестирования не хотим кропать, то нам все равно нужно вырезать центральный элемент (чтобы нейросеть отрабатывала на картинках одного размера)

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +    return cv2.flip(img, direction)
что-то мне сложно представить, когда мы можем хотеть делать вертикальный флип с нашими датасетами

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +    hsv = cv2.cvtColor(img1, cv2.COLOR_BGR2HSV)
а у нас картинки точно будут в bgr а не rgb?

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +    hsv[:, :, 0] += degree
есть ссылка, где оно так выполняется? я себе color jitter по-другому представлял

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +def mixup(img1, img2, y1, y2, alpha=1):
такой mixup не обязательно на уровне картинок выполнять, можно и на уровне фичей, так что можно заранее об этом подумать и  называть вход не img, а x или еще как-то

2019-04-03 09:20 UTC, konev-artem commented on data_provider/transform.py
> +def noisy_mixup(img1, img2, y1, y2, alpha=1, scale=0.025):
не хватает ссылки на статью, откуда эти нетривиальные методы взяты

2019-04-03 14:22 UTC, infected-mushroom commented on data_provider/transform.py
> +            img = f(img1, img2, y1, y2)
да, здесь и правда что-то странное.
наверное лучше выбирать одну случайную трансформацию из списка и применять только ее.

2019-04-03 14:46 UTC, infected-mushroom commented on data_provider/transform.py
> +def noisy_mixup(img1, img2, y1, y2, alpha=1, scale=0.025):
где и как ее лучше указать?
где-нибудь вообще в readme?

2019-04-04 05:15 UTC, konev-artem commented on data_provider/transform.py
> +def apply_random_classic_transform(img, p=0.5):
нужно оформить как класс, прокидывать тип прохода (трейн/тест) и параметры трансформаций

2019-04-05 15:59 UTC, infected-mushroom commented on data_provider/transform.py
> +    pass
реализовала саму функцию

2019-04-05 15:59 UTC, infected-mushroom commented on data_provider/transform.py
> +    return cv2.flip(img, direction)
убрала

2019-04-05 16:01 UTC, infected-mushroom commented on data_provider/transform.py
> +    hsv = cv2.cvtColor(img1, cv2.COLOR_BGR2HSV)
в cv2 стандартно считываются в BGR.
но поправила на RGB, будем считать, что в нем приходят картинки

2019-04-05 16:04 UTC, infected-mushroom commented on data_provider/transform.py
> +    hsv[:, :, 0] += degree
переписала, нужно проверить (Влад говорит, что вместо взятия остатка по модулю для saturation и value нужно ограничивать максимумом)

2019-04-05 17:48 UTC, vladiprof requested changes

2019-04-05 17:48 UTC, vladiprof commented on data_provider/transform.py
> +        hsv[:, :, 1] %= 256
max(256, hsv[:, :,1])

2019-04-05 17:48 UTC, vladiprof commented on data_provider/transform.py
> +        hsv[:, :, 2] %= 256
max(256, hsv[:, :,1])

2019-04-05 17:48 UTC, vladiprof commented on data_provider/transform.py
> +        # TODO: add constrains on crop size
сделать TODO, воможно, добавить параметр min_size

2019-04-07 20:12 UTC, closed without merging